= Betriebssysteme: Coding Cheatsheet
:toc:

== Sockets

``socket(int domain, int type, int protocol);``:: liefert einen Deskriptor für einen Kommunikationsendpunkt
	*``int domain`` Die Domain, in der die Kommunikation stattfinden soll
	* ``int type``: ``SOCK_STREAM``, ``SOCK_DGRAM`` oder ``SOCK_RAW`` definiert die Semantik der Kommunikation.
	* ``int protocol`` Spezifiziert das zu verwendende Protokoll, meist gibt es aber nur eines

---

``bind(sock, (struct sockaddr *) &server, sizeof(server));``:: bindet einen Namen an das Socket

	* ``sock`` Der in ``socket()`` erstellte Socket
	* ``(struct sockaddr *) &server`` Die Serverdaten, die wir manuell eingeben, stehen in einem Struct stehen:
	** sa_family_t sa_family;
	** char sa_data[14];
	* ``sizeof(server)`` Die größe des Servers

---

``listen(int socket, int backlog);``:: sorgt dafür, dass unsere Sockets Verbindungen Akzeptieren können.
	* ``int socket`` Der zu verwendende Socket
	* ``int backlog`` Maximale Länge der Queue der ausstehenden Verbindungen.

---

``accept(int sockfd, struckt sockaddr *addr, socklen_t *addrlen)``:: akzeptiert die eingehenden Verbindungen des Sockets
	* ``int sockfd`` Der mit ``socket()`` erstellte Socket, muss ``listen()``
	* ``struct sockaddr *addr`` Enthält die adresse des peer Sockets
	* ``socklen_t *addrlen`` Größe des Strcts von ``addr`` in Byte

---

``read(int fd, void *buf, size_t count)``:: Liest Daten aus einem Deskriptor aus
	* ``int fd`` der Verwendete Filedeskriptor aus ``socket()``
	* ``void *buf`` Der Buffer, in den die Daten geschrieben werden.
	* ``size_t count`` Größe der Bytes, die ausgelesen werden

---

``write(int fd, const void *buf, size_t count)``:: schreibt daten in den Filedeskriptor
	* ``int fd`` Der verwendete Filedeskriptor
	* ``const void *buf`` Der Buffer, der geschrieben werden soll
	* ``size_t count`` Anzahl der Bytes, die geschrieben werden sollen?

---

``close(int fd)``:: Schließt den Filedeskriptor
	* ``int fd`` Den zu schließenden Filedeskriptor

---

``select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)``::  Überwacht mehrere Filedeskriptoren, bis einer davon bereit ist, I/O-Operationen entgegen zu nehmen
	* ``int nfds`` Der höchste beschriebene Filedeskriptor + 1
	* ``fd_set *readfds`` Enthält Filedeskriptoren, aus denen glesen werden kann
	* ``fd_set *writefds`` Überprüft, ob schreibbare Bereiche vorhanden sind
	* ``fd_set *exceptfds`` Überprüft die Sockets nach Exceptions
	* ``struct timeval *timeout`` Definiert die Zeit bis zum Timeout

---

``int connect(int sockfd, const struct sockaddr *addr, socklen_t addrlen);``:: verbindet mit einem Socket
	* ``int sockfd`` Der zu Verbindende Socket.
	* ``const struct sockaddr *addr`` Die Adressdaten des Sockets
	* ``socklen_t addrlen`` Länge in Bytes des zu verwendenden Sockets

== Prozesse
``int fork()``:: erzeugt einen neuen Prozess

== Shared Memory
``int shmget(key_t key, size_t size, int shmflg);``:: holt/erzeugt ein Shared-memory segment
	* ``key_t key`` Der assoziierte Schlüssel zum Segment
	* ``size_t size`` Größe des Shared-memory Segementes
	* ``int shmflg`` Flag, die Bestimmt, ob wir ein neues Segment holen oder erstellen wollen (``IPC_CREAT``) oder auf jeden Fall erstellen wollen (``IPC_EXCL``), etc...

---

``void *shmat(int shmid, const void *shmaddr, int shmflg);``:: Hängt ein Segment an den Adressraum des aufrufenden Prozesses
	* ``int shmid`` ID des Shared Memory Segmentes
	* ``const void *shmaddr`` Adresse zur Einblendung des Segmentes in den Prozessraum, meist ``0``
	* ``int shmflg`` Flag, meist ``SHM_RND``, kann aber auch andere Funktionalitäten enthalten
	
---

``void shmdt(const void *shmaddr);``:: Hängt das Segment wieder ab.
	* ``const void *shmaddr`` Die Adresse des Segmentes //TODO Validieren
	
---

``int shmctl(int shmid, int cmd, struct shmid_ds *buf);``:: Kontrolliert das Shared Memory Segment
	* ``int shmid`` Das zu bearbeitende Segment
	* ``int cmd`` Das Kommando
	** ``IPC_STAT``, ``IPC_SET``, ``IPC_RMID``, ``IPC_INFO``, ``SHM_INFO``, ``SHM_STAT``, ``SHM_LOCK``, ``SHM_UNLOCK``
	* ``struct shmid_ds *buf`` Pointer auf ``shmid_ds`` Struct.
	
== Shared Memory

``int semget(key_t key, int nsems, int semflg)``:: Auf Semaphorengruppe zugreiffen oder eine neue Gruppe anlegen
	* ``key_t key`` Schlüssel der Gruppe, ``IPC_PRIVATE`` lässt den Unix-Kern den Schlüssel selbst erzeugen
	* ``int nsems`` Anzahl der Semaphoren in der Gruppe
	* ``int semflg`` Parameter der Gruppe, z.B. ``IPC_CREAT|xxxx``, wobei x die Zugriffsrechte kontrolliert.
	
---

``int semop(int semid, struct sembuf *sops, size_t nsops);``:: Führt eine Semaphorenoperation aus
	* ``int semid`` Schlüssel der Semaphorengruppe aus ``semget``
	* ``struct sembuf *sops`` Verweis auf Struct ``sembuf``, welches die Operationen definiert
		. ``short short sem_num`` Nummer des Semaphors in der Gruppe
		. ``short sem_op`` Bei >0 wird die Op zu einer UP-Operation, bei <0 zu einer DOWN-Operation
		. ``short sem_flg`` Enthält Flags zu Steuerung, optional.
		
---

``int semctl(int semid, int semnum, int cmd, ...);``:: Fürt eine Semaphorenoperation aus
	* ``int semid`` Key der Semaphorengruppe
	* ``int semnum`` Anzahl der Semaphore in der Gruppe
	* ``int cmd`` das auszuführende Kommando (``SETALL``, ``GETALL``, etc...)
		IPC_STAT::: Holt das semid_ds einer Semaphore
		IPC_SET::: Ändert Parameter aus ``sem_perm``
		IPC_RMID::: Entfernt ein Semaphorenset aus dem System
		GETVAL::: Liefert den Wert einer Semaphore
		SETVAL::: Setzt den Wert einer Semaphore
		GETPID::: Liefert den letzten Prozess, der eine semop durchgeführt hat
		GETNCNT::: Liefert die Anzahl der Prozesse die auf die Überschreitung einer Semaphore über einen bestimmten Wert warten.
		GETZCNT::: Gleiches wie oben, nur soll die Semaphore 0 werden.
		GETALL::: Liefert die Werte aller Semaphoren einer Gruppe
		SETALL::: Setzt alle Semaphoren einer Gruppe auf den gleichen Wert. 
	* ``...`` Optionales ``union semun arg``, welches bei manchen Operationen benötigt wird.
		. ``int val`` Wert für SETVAL
		. ``struct semid_ds *buf`` Buffer für IPC_STAT und IPC_SET
		. ``u_short *array`` Array für GETALL und SETALL

== Pipes und Programme

``pipe(...)``:: Ermöglicht unidirektionalen Prozessaustausch 
	* ``...`` Enthält ein Array mit einem Ein- und einem Ausgang der Pipe
	
---
	
``execlp(...)``:: Führt ein anderes Programm oder eine Datei aus.
	* ``...`` Enthält Programm mit sämmtlichen Parametern, wobei der erste und der zweite Parameter der Programmname selbst sein müssen.
	
== Nachrichtenwarteschlangen
``int msgget(key_t key, int msgflg)``:: Legt eine nachrichtenwarteschlange an
	* ``key_t key`` Schlüssel der Nachrichtenwarteschlange
	* ``intmsgflg`` ``IPC_CREAT|0664`` legt eine neue Schlange mit ``rw-r--r--`` Rechten
	
``int msgsnd(int msqid, const void *msgp, size_t msgsz, int msgflg)``
	* ``int msqid`` Schlüssel der Warteschlange
	* ``const void *msgp`` Typ und Inhalt der Warteschlange
	* ``size_t msgsz`` Größe der Daten
	* ``int msgflg`` Wird ausgeführt, wenn die Nachricht nicht gesendet werden kann.
	
``int msgrcv(int msqid, void *msgp, size_t msgsz, long msgtyp, int msgflg)``
	* ``int msqid`` Schlüssel der Warteschlange
	* ``void *msgp`` Typ und Aktuelle Daten, Rückmeldung
	* ``size_t msgsz`` Größe des Datenbereichs
	* ``int msgflg`` IPC_NOWAIT, wenn es keine passende Nachricht gibt